# === FONTS ===
font_mono    = "Monaspace Radon"
# font_mono  = "Iosevka Nerd Font"
# font_mono  = "Departure Mono"

font_display = "Bebas Neue"
# font_display = "Archivo"

font_size_sm = "11"
font_size_md = "13"
font_size_lg = "24"

# === CURSOR ===
cursor_theme = "Bibata-Modern-Classic"
# cursor_theme = "Bibata-Modern-Ice"
# cursor_theme = "capitaine-cursors"
# cursor_theme = "phinger-cursors-dark"

cursor_size  = "24"

# === BORDERS & SPACING ===
border_size    = "3"
gaps_inner     = "4"
gaps_outer     = "8"
corner_radius  = "0"

# === SHADOW ===
shadow_offset_x  = "2"
shadow_offset_y  = "2"
shadow_range     = "4"
shadow_render_power = "4"
